core/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login
from . import auth_decorators as auth_dec
from . import views as core_view


urlpatterns = [
    url(r'^$', core_view.LandingView.as_view(), name='LandingView'),
    # Login
    url(r'^login/$', auth_dec.user_passes_test(lambda u: auth_dec.auth_user_is_anonymous(u), '/bugs/')(login), name='login'),
    #url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'core.views.logout_view', name='logout'),
    # Bugs
    url(r'^bugs/$', login_required(core_view.BugListView.as_view()), name='BugListView'),
    url(r'^bugs/new/$', login_required(core_view.BugCreateView.as_view()), name='BugCreateView'),
    url(r'^bugs/update/(?P<pk>\d+)/$', login_required(core_view.BugUpdateView.as_view()), name='BugUpdateView'),
    # Users
    url(r'^users/$', auth_dec.user_passes_test(lambda u: auth_dec.auth_user_is_admin(u), '/bugs/')(core_view.UserListView.as_view()), name='UserListView'),
    url(r'^users/new/$', auth_dec.user_passes_test(lambda u: auth_dec.auth_user_is_admin(u), '/bugs/')(core_view.UserCreateView.as_view()), name='UserCreateView'),
    url(r'^users/delete/(?P<pk>\d+)/$', auth_dec.user_passes_test(lambda u: auth_dec.auth_user_is_admin(u), '/bugs/')(core_view.UserDeleteView.as_view()), name='UserDeleteView'),
]

evaluation/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace="core")),
]

core/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class EvalUser(AbstractUser):
    user_role = models.CharField(max_length=32, choices=(('admin', 'admin'), ('dev', 'dev'), ('support', 'support')), default='dev')

    REQUIRED_FIELDS = ['email']


class Bug(models.Model):
    owner = models.ForeignKey('core.EvalUser', related_name='bugs', related_query_name='bug', on_delete=models.SET_DEFAULT, default=1)
    assigned = models.ForeignKey('core.EvalUser', related_name='assigned_bugs', related_query_name='assigned_bug', on_delete=models.SET_DEFAULT, default=1)
    title = models.CharField(max_length=64)
    description = models.TextField()
    state = models.CharField(max_length=16, choices=(('open', 'open'), ('assigned', 'assigned'), ('closed', 'closed')), default='open')
    severity = models.CharField(max_length=16, choices=(('trivial', 'trivial'), ('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')), default='open')

    class Meta:
        app_label = 'core'
        verbose_name = "Bug"
        verbose_name_plural = "Bugs"

    def __str__(self):
        return str(self.title)

core/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from . import models as core_mod


# Create your views here.
def logout_view(request):
    logout(request)
    return redirect('/')


class LandingView(TemplateView):
    template_name = "core/index.html"

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            return redirect('core:BugListView')

        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class BugListView(ListView):
    model = core_mod.Bug
    template_name = "core/buglist.html"
    context_object_name = "bugs"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(BugListView, self).get_context_data(**kwargs)

        return context


class BugCreateView(CreateView):
    model = core_mod.Bug
    template_name = "core/newbug.html"
    fields = ['owner', 'assigned', 'title', 'description', 'state', 'severity']
    success_url = '/bugs/'

    def get_context_data(self, **kwargs):
        context = super(BugCreateView, self).get_context_data(**kwargs)

        return context


class BugUpdateView(UpdateView):
    model = core_mod.Bug
    template_name = "core/updatebug.html"
    fields = ['owner', 'assigned', 'title', 'description', 'state', 'severity']
    success_url = '/bugs/'

    def get_context_data(self, **kwargs):
        context = super(BugUpdateView, self).get_context_data(**kwargs)

        return context


class UserListView(ListView):
    model = core_mod.EvalUser
    template_name = "core/userlist.html"
    context_object_name = "users"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)

        return context


class UserCreateView(CreateView):
    model = core_mod.EvalUser
    template_name = "core/newuser.html"
    fields = ['username', 'password', 'email', 'user_role']
    success_url = '/users/'

    def get_context_data(self, **kwargs):
        context = super(UserCreateView, self).get_context_data(**kwargs)

        return context

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        self.object = form.save()
        self.object.set_password(form.cleaned_data.get('password'))
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class UserDeleteView(DeleteView):
    model = core_mod.EvalUser
    template_name = "core/deluser.html"
    success_url = '/users/'

    def get_context_data(self, **kwargs):
        context = super(UserDeleteView, self).get_context_data(**kwargs)

        return context

core/templates/core/buglist.html
{% extends 'base.html' %}

{% block content %}
    <div class="" style="margin-top: 30px;">
        <h2>Bug Listing</h2>
        <a class="btn btn-success" href="{% url 'core:BugCreateView' %}">+ Add New Bug</a>
        <table class="table table-bordered">
            <caption>Bugs In The System</caption>
            <thead>
                <tr>
                    <td>Title</td>
                    <td>Description</td>
                    <td>Owner</td>
                    <td>Assigned</td>
                    <td>State</td>
                    <td>Severity</td>
                </tr>
            </thead>
            <tbody>
                {% for bug in bugs %}
                    <tr>
                        <td><a href="{% url 'core:BugUpdateView' bug.id %}">{{ bug.title }}</a></td>
                        <td>{{ bug.description|truncatechars:32 }}</td>
                        <td>{{ bug.owner.username }}</td>
                        <td>{{ bug.assigned.username }}</td>
                        <td>{{ bug.state }}</td>
                        <td>{{ bug.severity }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{% url 'core:BugListView' %}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{% url 'core:BugListView' %}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    </div>
{% endblock %}

core/templates/core/deluser.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-6 col-md-offset-3" style="margin-top: 30px;">
        <h2>Remove User</h2>
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <h3>Are you sure you want to delete the user: "{{ object }}"?</h3>
            <input class="btn btn-danger" type="submit" value="Confirm" />
            <a class="btn btn-default" href="{% url 'core:UserListView' %}">Cancel</a>
        </form>
    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="center" style="text-align: center; margin-top: 30px;">
        <a class="btn btn-lg btn-default" href="{% url 'core:login' %}">Login</a>
    </div>
{% endblock %}

core/templates/core/newbug.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-6 col-md-offset-3" style="margin-top: 30px;">
        <h2>Submit A Bug</h2>
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Owner</label>
                <div class="col-sm-8">
                    {{ form.owner }}
                    {% if form.owner.errors %}
                        <ul class="errorlist">
                            {% for error in form.owner.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Assigned</label>
                <div class="col-sm-8">
                    {{ form.assigned }}
                    {% if form.assigned.errors %}
                        <ul class="errorlist">
                            {% for error in form.assigned.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Title</label>
                <div class="col-sm-8">
                    {{ form.title }}
                    {% if form.title.errors %}
                        <ul class="errorlist">
                            {% for error in form.title.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Description</label>
                <div class="col-sm-8">
                    {{ form.description }}
                    {% if form.description.errors %}
                        <ul class="errorlist">
                            {% for error in form.description.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">State</label>
                <div class="col-sm-8">
                    {{ form.state }}
                    {% if form.state.errors %}
                        <ul class="errorlist">
                            {% for error in form.state.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Severity</label>
                <div class="col-sm-8">
                    {{ form.severity }}
                    {% if form.severity.errors %}
                        <ul class="errorlist">
                            {% for error in form.severity.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <input class="btn btn-lg btn-success" type="submit" value="Submit Bug" />
            <a class="btn btn-lg btn-danger" href="{% url 'core:BugListView' %}">Back To Bug List</a>
        </form>
    </div>
{% endblock %}

core/templates/core/newuser.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-6 col-md-offset-3" style="margin-top: 30px;">
        <h2>Create A User</h2>
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Username</label>
                <div class="col-sm-8">
                    {{ form.username }}
                    {% if form.username.errors %}
                        <ul class="errorlist">
                            {% for error in form.username.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Password</label>
                <div class="col-sm-8">
                    <input type="password" name="password" id="id_password" />
                    {% if form.password.errors %}
                        <ul class="errorlist">
                            {% for error in form.password.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Email</label>
                <div class="col-sm-8">
                    {{ form.email }}
                    {% if form.email.errors %}
                        <ul class="errorlist">
                            {% for error in form.email.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Role</label>
                <div class="col-sm-8">
                    {{ form.user_role }}
                    {% if form.user_role.errors %}
                        <ul class="errorlist">
                            {% for error in form.user_role.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <input class="btn btn-lg btn-success" type="submit" value="Create New User" />
            <a class="btn btn-lg btn-danger" href="{% url 'core:UserListView' %}">Back To User List</a>
        </form>
    </div>
{% endblock %}

core/templates/core/updatebug.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-6 col-md-offset-3" style="margin-top: 30px;">
        <h2>Update Bug Details</h2>
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Owner</label>
                <div class="col-sm-8">
                    {{ form.owner }}
                    {% if form.owner.errors %}
                        <ul class="errorlist">
                            {% for error in form.owner.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Assigned</label>
                <div class="col-sm-8">
                    {{ form.assigned }}
                    {% if form.assigned.errors %}
                        <ul class="errorlist">
                            {% for error in form.assigned.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Title</label>
                <div class="col-sm-8">
                    {{ form.title }}
                    {% if form.title.errors %}
                        <ul class="errorlist">
                            {% for error in form.title.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Description</label>
                <div class="col-sm-8">
                    {{ form.description }}
                    {% if form.description.errors %}
                        <ul class="errorlist">
                            {% for error in form.description.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">State</label>
                <div class="col-sm-8">
                    {{ form.state }}
                    {% if form.state.errors %}
                        <ul class="errorlist">
                            {% for error in form.state.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-4 control-label">Severity</label>
                <div class="col-sm-8">
                    {{ form.severity }}
                    {% if form.severity.errors %}
                        <ul class="errorlist">
                            {% for error in form.severity.errors %}
                                <li><p class="bg-danger">{{ error|escape }}</p></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <input class="btn btn-lg btn-success" type="submit" value="Update Bug" />
            <a class="btn btn-lg btn-danger" href="{% url 'core:BugListView' %}">Back To Bug List</a>
        </form>
    </div>
{% endblock %}

core/templates/core/userlist.html
{% extends 'base.html' %}

{% block content %}
    <div class="" style="margin-top: 30px;">
        <h2>User Listing</h2>
        <a class="btn btn-success" href="{% url 'core:UserCreateView' %}">+ Add New user</a>
        <table class="table table-bordered">
            <caption>Users In The System</caption>
            <thead>
                <tr>
                    <td>Username</td>
                    <td>Email</td>
                    <td>Role</td>
                    <td>Actions</td>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.user_role }}</td>
                        <td><a class="btn btn-sm btn-danger" href="{% url 'core:UserDeleteView' user.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{% url 'core:UserListView' %}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{% url 'core:UserListView' %}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Evaluation</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3" style="text-align: center;">
                        {% block header %}<h1>Evaluation Project</h1>{% endblock %}
                    </div>
                </div>
                {% if request.user.is_authenticated %}
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="col-md-4">
                                <a class="btn btn-default btn-block" href="{% url 'core:BugListView' %}">Bug Listing</a>
                            </div>
                            <div class="col-md-4">
                                <a class="btn btn-default btn-block" {% if request.user.user_role != 'admin' %} href="#" disabled{% else %} href="{% url 'core:UserListView' %}" {% endif %}>Manage Users</a>
                            </div>
                            <div class="col-md-4">
                                <a class="btn btn-default btn-block" href="{% url 'core:logout' %}">Logout</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-md-12">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>